Repository CS450-ECE461/fall2018-group2, pull requests merged in 2018-12, with the labels that each got.

#84 Reintegrated review model for blueprint
  blueprint-experiences/app/controllers/review.js
  blueprint-experiences/app/models/review.js
  blueprint-experiences/app/routers/v1/review.js
  blueprint-experiences/app/seeds/mongodb/$default.js
Labels: integration

#85 integrate individual experience with data from backend
  ember-experiences/app/routes/experience.js
  ember-experiences/app/routes/experience/index.js
  ember-experiences/app/templates/components/search-bar.hbs
Labels: integration

#118 Adds remote images to experiences
  blueprint-experiences/app/configs/server.js
  blueprint-experiences/app/models/experience.js
  blueprint-experiences/app/seeds/mongodb/$default.js
  blueprint-experiences/public_html/images/bunny-hiking.png
  blueprint-experiences/public_html/images/cooking-class.jpg
  blueprint-experiences/public_html/images/cooking-dinner.jpg
  blueprint-experiences/public_html/images/dalmatians.jpg
  blueprint-experiences/public_html/images/dog-hiking.jpg
  blueprint-experiences/public_html/images/dogs.jpg
  blueprint-experiences/public_html/images/exercise-indoors.jpeg
  blueprint-experiences/public_html/images/exercise-outdoors.jpg
  blueprint-experiences/public_html/images/frogger-highway.png
  blueprint-experiences/public_html/images/hitch-hike.jpg
  blueprint-experiences/public_html/images/home-dinner.jpg
  blueprint-experiences/public_html/images/human_tetris.jpg
  blueprint-experiences/public_html/images/jump-rope.jpg
  blueprint-experiences/public_html/images/map.png
  blueprint-experiences/public_html/images/meditate.jpg
  blueprint-experiences/public_html/images/segues.jpg
  blueprint-experiences/public_html/images/tetris.jpg
  blueprint-experiences/public_html/images/turtle.jpg
  blueprint-experiences/public_html/images/yoga-class.jpg
  blueprint-experiences/public_html/images/yoga-stretch.jpg
  blueprint-experiences/public_html/images/yoha-again.jpeg
Labels: integration

#123 made back button on Experience page functional
  ember-experiences/app/components/header-bar.js
  ember-experiences/app/templates/components/header-bar.hbs
  ember-experiences/app/templates/experience/index.hbs
Labels: enhancement, integration

#127 Integrates booking and favorites
  blueprint-experiences/app/controllers/booking.js
  blueprint-experiences/app/controllers/favorite.js
  blueprint-experiences/app/seeds/mongodb/$default.js
  ember-experiences/app/models/booking.js
  ember-experiences/app/models/favorite.js
  ember-experiences/app/routes/nav-enabled/experiences.js
  ember-experiences/app/templates/nav-enabled/experiences/favorites.hbs
  ember-experiences/app/templates/nav-enabled/experiences/index.hbs
  ember-experiences/tests/unit/models/booking-test.js
  ember-experiences/tests/unit/models/favorite-test.js
Labels: integration

#128 Update seed with titles for experiences
  blueprint-experiences/app/seeds/mongodb/$default.js
Labels: integration

#137 Update experience images
  blueprint-experiences/app/seeds/mongodb/$default.js
Labels: frontend
