Repository CS450-ECE461/fall2018-group2, pull requests merged in 2018-11, with the labels that each got.

#13 Implemented User model and mongoDB seed - csneto
  blueprint-experiences/app/configs/app.js
  blueprint-experiences/app/configs/gatekeeper.js
  blueprint-experiences/app/configs/mongodb.js
  blueprint-experiences/app/configs/server.js
  blueprint-experiences/app/controllers/user.js
  blueprint-experiences/app/models/user.js
  blueprint-experiences/app/policies/role.js
  blueprint-experiences/app/routers/endpoint.js
  blueprint-experiences/app/routers/v1.js
  blueprint-experiences/app/routers/v1/user.js
  blueprint-experiences/app/seeds/mongodb/$default.js
  blueprint-experiences/package-lock.json
  blueprint-experiences/package.json
  blueprint-experiences/tests/unit-tests/app/routers/user-test.js
Labels: backend

#36 Fixed gatekeeper on sign-in route
  blueprint-experiences/app/routers/endpoint.js
  blueprint-experiences/app/routers/v1.js
  blueprint-experiences/app/seeds/mongodb/$default.js
  ember-experiences/app/adapters/application.js
  ember-experiences/app/routes/experience.js
  ember-experiences/app/routes/experience/conversation.js
  ember-experiences/app/routes/experiences/favorites.js
  ember-experiences/app/routes/nav-enabled/experiences.js
  ember-experiences/app/routes/nav-enabled/explore.js
  ember-experiences/app/routes/nav-enabled/profile.js
  ember-experiences/config/environment.js
  ember-experiences/package-lock.json
Labels: frontend, integration

#37 Made client_id static
  blueprint-experiences/app/seeds/mongodb/$default.js
  ember-experiences/config/environment.js
Labels: backend, enhancement, frontend

#42 Protect /v1
  blueprint-experiences/app/routers/endpoint.js
  blueprint-experiences/app/routers/v1.js
Labels: backend, integration

#46 Issue45
  ember-experiences/app/styles/components/_nav-bar.scss
  ember-experiences/app/templates/components/nav-bar.hbs
  ember-experiences/public/assets/icons/AddFolder.svg
  ember-experiences/public/assets/icons/BackArrow.svg
  ember-experiences/public/assets/icons/Calendar-Selected.svg
  ember-experiences/public/assets/icons/Calendar-Unselected.svg
  ember-experiences/public/assets/icons/Close.svg
  ember-experiences/public/assets/icons/Delete.svg
  ember-experiences/public/assets/icons/Edit-Selected.svg
  ember-experiences/public/assets/icons/Edit-Unselected.svg
  ember-experiences/public/assets/icons/Explore-Selected.svg
  ember-experiences/public/assets/icons/Explore-Unselected.svg
  ember-experiences/public/assets/icons/Guests-Selected.svg
  ember-experiences/public/assets/icons/Guests-Unselected.svg
  ember-experiences/public/assets/icons/LeftArrow.svg
  ember-experiences/public/assets/icons/Location-Selected.svg
  ember-experiences/public/assets/icons/Location-Unselected.svg
  ember-experiences/public/assets/icons/MyExperiences-Selected.svg
  ember-experiences/public/assets/icons/MyExperiences-Unselected.svg
  ember-experiences/public/assets/icons/Price-Selected.svg
  ember-experiences/public/assets/icons/Price-Unselected.svg
  ember-experiences/public/assets/icons/Profile-Selected.svg
  ember-experiences/public/assets/icons/Profile-Unselected.svg
  ember-experiences/public/assets/icons/RatingStars.svg
  ember-experiences/public/assets/icons/RightArrow.svg
  ember-experiences/public/assets/icons/Saved-Selected.svg
  ember-experiences/public/assets/icons/Saved-Unselected.svg
  ember-experiences/public/assets/icons/Search.svg
  ember-experiences/public/assets/icons/Time.svg
  ember-experiences/public/assets/images/calendar-alt.svg
  ember-experiences/public/assets/images/home.svg
  ember-experiences/public/assets/images/star.svg
  ember-experiences/public/assets/images/user.svg
Labels: frontend

#49 Issue48
  ember-experiences/app/components/featured-carousel.js
  ember-experiences/app/components/featured-listing.js
  ember-experiences/app/styles/_components.scss
  ember-experiences/app/styles/app.scss
  ember-experiences/app/styles/components/_featured-carousel.scss
  ember-experiences/app/styles/components/_featured-experience.scss
  ember-experiences/app/styles/components/_featured-listing.scss
  ember-experiences/app/templates/components/featured-carousel.hbs
  ember-experiences/app/templates/components/featured-listing.hbs
  ember-experiences/app/templates/nav-enabled/explore.hbs
  ember-experiences/bower.json
  ember-experiences/package-lock.json
  ember-experiences/package.json
  ember-experiences/tests/integration/components/featured-carousel-test.js
  ember-experiences/tests/integration/components/featured-listing-test.js
Labels: enhancement, frontend

#53 Updated models
  blueprint-experiences/app/controllers/event.js
  blueprint-experiences/app/controllers/experience.js
  blueprint-experiences/app/models/event.js
  blueprint-experiences/app/models/experience.js
  blueprint-experiences/app/routers/v1/event.js
  blueprint-experiences/app/seeds/mongodb/$default.js
  blueprint-experiences/app/services/experiences.js
  blueprint-experiences/tests/unit-tests/app/routers/user-test.js
Labels: backend

#56 Update to RESTAdapter and RESTSerializer
  ember-experiences/app/adapters/application.js
  ember-experiences/app/serializers/application.js
  ember-experiences/tests/unit/serializers/application-test.js
Labels: enhancement, integration

#59 Updates models
  blueprint-experiences/app/models/user.js
  blueprint-experiences/app/seeds/mongodb/$default.js
  blueprint-experiences/tests/unit-tests/app/routers/user-test.js
  ember-experiences/app/models/experience.js
  ember-experiences/app/models/user.js
  ember-experiences/package-lock.json
Labels: integration
